In [32]:
import pandas as pd

In [33]:
df = pd.read_csv('../data/raw/02_nav_history - Copy.csv')
df.head(5)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

In [34]:
from datetime import datetime
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')

In [35]:
df = df.sort_values(by=['amfi_code', 'date'])

In [36]:
df['nav'].isnull().sum()

np.int64(0)

In [37]:
df.duplicated().sum()

np.int64(0)

In [38]:
(df['nav'] <= 0).sum()

np.int64(0)

In [39]:
df = df.reset_index(drop=True)

In [40]:
investor_trans = pd.read_csv('../data/raw/08_investor_transactions.csv')
investor_trans.head(5)

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [41]:
investor_trans["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [42]:
investor_trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB

In [43]:
investor_trans['transaction_date'] = pd.to_datetime(investor_trans['transaction_date'] ,format='%Y-%m-%d')

In [44]:
(investor_trans['annual_income_lakh'] <= 0).sum()

np.int64(0)

In [45]:
(investor_trans['amount_inr'] <= 0).sum()

np.int64(0)

In [46]:
investor_trans['kyc_status'].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [27]:
scheme_perfo = pd.read_csv('../data/raw/07_scheme_performance.csv')
scheme_perfo.head(5)

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [28]:
scheme_perfo.info()
scheme_perfo.describe()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

,amfi_code,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.00000,40.000000,40.000000
mean,120247.000000,14.376000,14.089000,14.516750,12.835500,1.253500,0.873250,1.361750,2.082500,14.962500,-19.200250,26091.60000,1.237000,4.250000
std,14534.998667,4.883023,4.617253,4.454021,4.740972,0.447412,0.224846,1.475805,2.203144,6.669282,8.819164,13809.11134,0.386584,0.742484
min,100016.000000,4.260000,5.140000,5.430000,3.960000,0.510000,0.220000,0.800000,1.030000,0.500000,-33.500000,979.00000,0.550000,3.000000
25%,118632.750000,11.735000,12.035000,12.340000,10.690000,0.887500,0.890000,0.865000,1.270000,14.000000,-25.062500,17400.50000,0.787500,4.000000
50%,119551.500000,14.620000,14.205000,14.185000,13.090000,1.205000,0.960000,0.925000,1.445000,14.000000,-20.600000,26713.00000,1.425000,4.000000
75%,120842.250000,16.392500,15.882500,17.585000,14.775000,1.700000,1.000000,0.985000,1.637500,19.000000,-14.255000,38125.00000,1.540000,5.000000
max,149324.000000,24.930000,23.390000,23.800000,22.160000,1.980000,1.040000,7.680000,10.370000,25.000000,-2.230000,49046.00000,1.640000,5.000000

In [29]:
df.to_csv(
    "../data/processed/nav_history_clean.csv",
    index=False
)

In [47]:
investor_trans.to_csv(
    "../data/processed/investor_transactions_clean.csv",
    index=False
)

In [31]:
scheme_perfo.to_csv(
    "../data/processed/scheme_performance_clean.csv",
    index=False
)

In [50]:
import sqlite3

In [51]:
conn = sqlite3.connect("../data/db/bluestock_mf.db")

In [52]:
print("Database created successfully")

Database created successfully

In [53]:
import pandas as pd

nav = pd.read_csv("../data/processed/nav_history_clean.csv")

nav.to_sql(
    "fact_nav",
    conn,
    if_exists="replace",
    index=False
)

46000

In [54]:
transactions = pd.read_csv(
    "../data/processed/investor_transactions_clean.csv"
)

transactions.to_sql(
    "fact_transactions",
    conn,
    if_exists="replace",
    index=False
)

32778

In [55]:
performance = pd.read_csv(
    "../data/processed/scheme_performance_clean.csv"
)

performance.to_sql(
    "fact_performance",
    conn,
    if_exists="replace",
    index=False
)

40

In [56]:
cursor = conn.cursor()

cursor.execute(
    "SELECT name FROM sqlite_master WHERE type='table';"
)

print(cursor.fetchall())

[('fact_nav',), ('fact_transactions',), ('fact_performance',)]

In [57]:
pd.read_sql(
    "SELECT * FROM fact_nav LIMIT 5",
    conn
)

   amfi_code        date       nav
0     100016  2022-01-03  520.4608
1     100016  2022-01-04  515.0971
2     100016  2022-01-05  521.7239
3     100016  2022-01-06  515.7880
4     100016  2022-01-07  515.1639

In [58]:
import sqlite3

conn = sqlite3.connect("../data/db/bluestock_mf.db")

In [60]:
fund = pd.read_csv("../data/raw/01_fund_master - Copy.csv")
fund.head(5)
fund.info()
fund.isnull().sum()
fund.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

np.int64(0)

In [71]:
fund.to_csv(
    "../data/processed/fund_master_clean.csv",
    index=False
)

In [74]:
aum = pd.read_csv("../data/raw/03_aum_by_fund_house - Copy.csv")
aum.info()
aum.describe()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     str
 1   fund_house      90 non-null     str
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 3.6 KB

       aum_lakh_crore     aum_crore  num_schemes
count       90.000000  9.000000e+01    90.000000
mean         4.352889  4.352889e+05   152.200000
std          2.734328  2.734328e+05    52.108832
min          1.050000  1.050000e+05    56.000000
25%          2.525000  2.525000e+05    95.000000
50%          3.450000  3.450000e+05   172.500000
75%          5.675000  5.675000e+05   195.000000
max         12.500000  1.250000e+06   216.000000

In [75]:
aum.duplicated().sum()

np.int64(0)

In [77]:
aum.to_csv(
    "../data/processed/aum_by_fund_house_clean.csv",
    index=False
)

In [78]:
fund.to_sql(
    "dim_fund",
    conn,
    if_exists="replace",
    index=False
)

aum.to_sql(
    "fact_aum",
    conn,
    if_exists="replace",
    index=False
)

90

In [80]:
aum["date"] = pd.to_datetime(aum["date"])

aum.to_csv(
    "../data/processed/aum_by_fund_house_clean.csv",
    index=False
)

In [81]:
aum.to_sql(
    "fact_aum",
    conn,
    if_exists="replace",
    index=False
)

90

In [82]:
aum.dtypes

date              datetime64[us]
fund_house                   str
aum_lakh_crore           float64
aum_crore                  int64
num_schemes                int64
dtype: object

In [83]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("../data/db/bluestock_mf.db")

csv_rows = len(pd.read_csv("../data/processed/nav_history_clean.csv"))

sql_rows = pd.read_sql(
    "SELECT COUNT(*) as cnt FROM fact_nav",
    conn
)["cnt"][0]

print("CSV Rows:", csv_rows)
print("SQLite Rows:", sql_rows)

CSV Rows: 46000
SQLite Rows: 46000

In [84]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("../data/db/bluestock_mf.db")

for table in [
    "dim_fund",
    "fact_nav",
    "fact_transactions",
    "fact_performance",
    "fact_aum"
]:
    cnt = pd.read_sql(
        f"SELECT COUNT(*) as rows FROM {table}",
        conn
    )
    print(table)
    print(cnt)

dim_fund
   rows
0    40
fact_nav
    rows
0  46000
fact_transactions
    rows
0  32778
fact_performance
   rows
0    40
fact_aum
   rows
0    90